version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  deploy_prod:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: sudo npm install -g firebase-tools
      - run: firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build_deploy:
    jobs:
    - lint
    - build
    - deploy_prod:
        requires:
          - lint
          - build
        filters:
          branches:
            only: master
