version: 2
jobs:
  build:
    docker:
    - image: circleci/node
    branches:
      only:
      - master
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: npm install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: npm run build
    - run: sudo npm install -g firebase-tools
    - run: firebase deploy --token "$FIREBASE_TOKEN"

