version: 2
jobs:
  build:
    docker:
    - image: circleci/node
    branches:
      only:
      - master
    steps:
    - checkout
    - run: sudo npm install -g node-pre-gyp
    - run: sudo npm install -g firebase-tools
    - run: npm install --no-optional
    - run: npm run build
    - run: firebase deploy --token "$FIREBASE_TOKEN"

